# Generated by Django 6.0 on 2025-12-04 00:19

import cases.models
import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('national_id', models.CharField(max_length=30, unique=True)),
                ('birth_certificate_number', models.CharField(max_length=30)),
                ('date_of_birth', django_jalali.db.models.jDateField()),
                ('birth_place', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('F', 'زن'), ('O', 'Other')], max_length=1)),
                ('education', models.CharField(max_length=30)),
                ('field_of_study', models.CharField(max_length=30)),
                ('insurance', models.CharField(max_length=30)),
                ('job', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('home_phone_number', models.CharField(max_length=30)),
                ('housing_status', models.CharField(max_length=30)),
                ('residencial_area', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('pension_status', models.CharField(max_length=30)),
                ('case_type', models.CharField(max_length=30)),
                ('bank_card_number', models.CharField(max_length=30)),
                ('bank_account_number', models.CharField(max_length=30)),
                ('bank_shaba_number', models.CharField(max_length=30)),
                ('marrige_status', models.CharField(max_length=30)),
                ('brothers_count', models.IntegerField()),
                ('sisters_count', models.IntegerField()),
                ('dependents_count', models.IntegerField()),
                ('children_count', models.IntegerField()),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=cases.models.get_file_path)),
                ('doc_type', models.CharField(max_length=30)),
                ('date', django_jalali.db.models.jDateField()),
                ('expiry_date', django_jalali.db.models.jDateField()),
                ('expiry_diuration', models.CharField(max_length=30)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseFamilyMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('national_id', models.CharField(max_length=30)),
                ('education', models.CharField(max_length=30)),
                ('job', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=500)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
        ),
    ]
