# Generated by Django 6.0 on 2025-12-04 00:56

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='case',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره حساب'),
        ),
        migrations.AlterField(
            model_name='case',
            name='bank_card_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره کارت'),
        ),
        migrations.AlterField(
            model_name='case',
            name='bank_shaba_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره شبا'),
        ),
        migrations.AlterField(
            model_name='case',
            name='birth_certificate_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره شناسنامه'),
        ),
        migrations.AlterField(
            model_name='case',
            name='birth_place',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='محل تولد'),
        ),
        migrations.AlterField(
            model_name='case',
            name='brothers_count',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True, verbose_name='تعداد برادران'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(blank=True, choices=[('rehab', 'توانبخشی'), ('social', 'اجتماعی'), ('recovered', 'بهبود یافته')], max_length=30, null=True, verbose_name='نوع پرونده'),
        ),
        migrations.AlterField(
            model_name='case',
            name='children_count',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True, verbose_name='تعداد فرزندان'),
        ),
        migrations.AlterField(
            model_name='case',
            name='date_of_birth',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='case',
            name='dependents_count',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True, verbose_name='تعداد افراد تحت تکفل'),
        ),
        migrations.AlterField(
            model_name='case',
            name='education',
            field=models.CharField(blank=True, choices=[('illiterate', 'بی سواد'), ('elementary', 'ابتدایی'), ('middle_school', 'متوسطه اول (سیکل)'), ('high_school', 'متوسطه دوم (دیپلم)'), ('associate', 'کاردانی (فوق دیپلم)'), ('bachelor', 'کارشناسی (لیسانس)'), ('master', 'کارشناسی ارشد (فوق لیسانس)'), ('phd', 'دکترا'), ('post_doc', 'فوق دکترا')], max_length=30, null=True, verbose_name='تحصیلات'),
        ),
        migrations.AlterField(
            model_name='case',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='رشته تحصیلی'),
        ),
        migrations.AlterField(
            model_name='case',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='case',
            name='gender',
            field=models.CharField(choices=[('M', 'مرد'), ('F', 'زن'), ('O', 'سایر')], max_length=1, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='case',
            name='home_phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='تلفن ثابت'),
        ),
        migrations.AlterField(
            model_name='case',
            name='housing_status',
            field=models.CharField(blank=True, choices=[('rental', 'استیجاری'), ('paternal', 'پدری'), ('relatives', 'منزل بستگان'), ('endowment', 'مسکن وقفی'), ('owned', 'مسکن شخصی'), ('homeless', 'بی خانمان'), ('inherited', 'ورثه ای'), ('org_housing', 'منازل سازمانی'), ('care_center', 'مرکز نگهداری')], max_length=30, null=True, verbose_name='وضعیت مسکن'),
        ),
        migrations.AlterField(
            model_name='case',
            name='insurance',
            field=models.CharField(blank=True, choices=[('none', 'ندارد'), ('social_security', 'تامین اجتماعی'), ('welfare', 'بهزیستی'), ('carpet_weaving', 'قالی بافی'), ('self_employed', 'خویش فرمایی'), ('life', 'عمر'), ('employer', 'کارفرمایی'), ('labor', 'کارگری'), ('medical_services', 'خدمات درمانی'), ('housewives', 'زنان خانه دار'), ('rural', 'روستاییان'), ('iranian_health', 'سلامت ایرانیان'), ('universal_health', 'سلامت همگانی'), ('gov_employees', 'سلامت - کارکنان دولت'), ('other_sectors', 'سلامت - سایر اقشار'), ('armed_forces', 'نیروهای مسلح'), ('special_patients', 'بیماران خاص')], max_length=30, null=True, verbose_name='وضعیت بیمه'),
        ),
        migrations.AlterField(
            model_name='case',
            name='job',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شغل'),
        ),
        migrations.AlterField(
            model_name='case',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='case',
            name='marrige_status',
            field=models.CharField(blank=True, choices=[('married', 'متاهل'), ('divorced', 'مطلقه'), ('separated', 'متارکه'), ('single', 'مجرد'), ('widowed', 'همسر فوت شده')], max_length=30, null=True, verbose_name='وضعیت تاهل'),
        ),
        migrations.AlterField(
            model_name='case',
            name='national_id',
            field=models.CharField(max_length=30, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='case',
            name='pension_status',
            field=models.CharField(blank=True, choices=[('continuous', 'مستمر'), ('non_continuous', 'غیرمستمر')], max_length=30, null=True, verbose_name='وضعیت مستمری'),
        ),
        migrations.AlterField(
            model_name='case',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره همراه'),
        ),
        migrations.AlterField(
            model_name='case',
            name='residencial_area',
            field=models.CharField(blank=True, choices=[('industrial_city', 'شهر صنعتی'), ('railway', 'راه آهن'), ('gerdo_town', 'شهرک گردو'), ('shariati', 'شریعتی'), ('maskan', 'مسکن'), ('alamolhoda', 'علم الهدی'), ('rodaki', 'رودکی'), ('khorram', 'خرم'), ('hossein_abad', 'حسین آباد'), ('nazm_abad', 'نظم آباد'), ('karahroud', 'کرهرود'), ('jahan_panah', 'جهان پناه'), ('malek', 'ملک'), ('abbas_abad', 'عباس آباد'), ('valiasr_town', 'شهرک ولی عصر'), ('robat_mil', 'رباط میل'), ('ban', 'بان'), ('jahangiri', 'جهانگیری')], max_length=30, null=True, verbose_name='منطقه مسکونی'),
        ),
        migrations.AlterField(
            model_name='case',
            name='sisters_count',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True, verbose_name='تعداد خواهران'),
        ),
    ]
