# Generated by Django 6.0 on 2025-12-04 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_case_address_alter_case_bank_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disability_type', models.CharField(max_length=30, verbose_name='نوع معلولیت')),
                ('disability_level', models.CharField(max_length=30, verbose_name='شدت معلولیت')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disabilities', to='cases.case')),
            ],
        ),
    ]
