# Generated by Django 6.0 on 2025-12-04 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_disability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefamilymembers',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='casefamilymembers',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='casefamilymembers',
            name='education',
            field=models.CharField(max_length=30, verbose_name='تحصیلات'),
        ),
        migrations.AlterField(
            model_name='casefamilymembers',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='casefamilymembers',
            name='job',
            field=models.CharField(max_length=30, verbose_name='شغل'),
        ),
        migrations.AlterField(
            model_name='casefamilymembers',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='casefamilymembers',
            name='national_id',
            field=models.CharField(max_length=30, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='casefamilymembers',
            name='relation',
            field=models.CharField(choices=[('father', 'پدر'), ('mother', 'مادر'), ('brother', 'برادر'), ('sister', 'خواهر'), ('son', 'پسر'), ('daughter', 'دختر')], max_length=30, verbose_name='نسبت'),
        ),
        migrations.CreateModel(
            name='ReasonCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='cases.case', verbose_name='علت تشکیل پرونده')),
            ],
        ),
    ]
