# Generated by Django 6.0 on 2025-12-04 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_casefamilymembers_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='military_serveice',
            field=models.CharField(blank=True, choices=[('absence', 'غیبت'), ('exempt', 'معاف'), ('passed', 'گدرانده')], max_length=30, null=True, verbose_name='وضعیت سربازی'),
        ),
        migrations.AlterField(
            model_name='reasoncase',
            name='reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='RecoveredReasonCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, choices=[('employment_loan', 'وام اشتفال'), ('insurance_right', 'حق بیمه'), ('cost_reduction', 'کاهش هزینه انشعابات')], max_length=500, null=True)),
                ('skill', models.CharField(blank=True, max_length=500, null=True)),
                ('work_experience', models.CharField(blank=True, max_length=500, null=True)),
                ('insurance_type', models.CharField(blank=True, choices=[('self', 'خویش فرمایی'), ('employes', 'کارفرمایی')], max_length=500, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovered_reasons', to='cases.case', verbose_name='علت تشکیل پرونده (بهبود یافته)')),
            ],
        ),
    ]
