# Generated by Django 6.0 on 2025-12-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_military_serveice_alter_reasoncase_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefamilymembers',
            name='education',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='تحصیلات'),
        ),
        migrations.AlterField(
            model_name='casefamilymembers',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='casefamilymembers',
            name='job',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شغل'),
        ),
        migrations.AlterField(
            model_name='casefamilymembers',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='casefamilymembers',
            name='national_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='disability',
            name='disability_level',
            field=models.CharField(choices=[('level1', 'خفیف'), ('level2', 'متوسط'), ('level3', 'شدید'), ('level4', 'خیلی شدید'), ('none', 'ندارد')], max_length=30, verbose_name='شدت معلولیت'),
        ),
        migrations.AlterField(
            model_name='disability',
            name='disability_type',
            field=models.CharField(choices=[('body_movment', 'جسمی حرکتی'), ('body_movment_ms', 'جسمی حرکتی ام اس'), ('nerves_psyche', 'اعصاب و روان'), ('hearing', 'شنوایی'), ('vision', 'بینایی'), ('mental', 'ذهنی'), ('spoken', 'گفتاری'), ('autism', 'اوتیسم'), ('spinal_cord', 'ذایعه نخاعی'), ('old_age', 'سامندی'), ('alzheimer', 'آلذایمر'), ('dementia', 'دمانسس'), ('no_disability', 'بدون معلولیت'), ('no_document', 'بدون سند')], max_length=30, verbose_name='نوع معلولیت'),
        ),
        migrations.AlterField(
            model_name='reasoncase',
            name='reason',
            field=models.CharField(blank=True, choices=[('man_cant_work', 'مرد از کار افتاده'), ('husbend_died', 'شوهر فوت شده'), ('divorce', 'طلاق گرفته'), ('self_governing_girl', 'دختر خود سرپرست'), ('bad_guardian_girl', 'دختر بد سرپرست'), ('leaved_partner', 'متارکه کرده'), ('no_family_child', 'کودک فاقد سرپرست')], max_length=500, null=True),
        ),
    ]
