# Generated by Django 6.0 on 2025-12-04 17:10

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_alter_casefamilymembers_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedocuments',
            name='date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casedocuments',
            name='doc_type',
            field=models.CharField(choices=[('commition', 'کمیسیون'), ('needs_form', 'تعیین نیاز'), ('birt_certificat', 'شناسنامه'), ('disabiliti_card', 'کارت معلولیت'), ('national_id', 'کارت ملی'), ('bank', 'مدارک بانکی'), ('military_serveice', 'کارت پایان خدمت'), ('pic3x4', 'عکس 3x4'), ('rehab_tools', 'لوازم توانبخشی'), ('military_exemtion', 'کارت معافیت از خدمت'), ('foreign_national_id', 'کارت اقامت اتباع خارجی'), ('insurance', 'بیمه'), ('divorce_id', 'طلاق نامه'), ('death_certificate', 'گواهی فوت'), ('children_docs', 'مدارک فرزندان'), ('skill_certificate', 'گواهی مهارت'), ('other', 'متفرقه')], max_length=30),
        ),
        migrations.AlterField(
            model_name='casedocuments',
            name='expiry_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casedocuments',
            name='expiry_diuration',
            field=models.IntegerField(blank=True, choices=[(5, '5 سال بعد'), (10, '10 سال بعد'), (1, '1 سال بعد'), (2, '2 سال بعد'), (3, '3 سال بعد'), (4, '4 سال بعد'), (6, '6 سال بعد'), (7, '7 سال بعد'), (8, '8 سال بعد'), (9, '9 سال بعد'), (0.5, '6 ماه بعد')], null=True),
        ),
    ]
