# Generated by Django 6.0 on 2025-12-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_alter_casedocuments_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='case',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رشته تحصیلی'),
        ),
        migrations.AlterField(
            model_name='case',
            name='insurance',
            field=models.CharField(blank=True, choices=[('none', 'ندارد'), ('social_security', 'تامین اجتماعی'), ('welfare', 'بهزیستی'), ('carpet_weaving', 'قالی بافی'), ('self_employed', 'خویش فرمایی'), ('life', 'عمر'), ('employer', 'کارفرمایی'), ('labor', 'کارگری'), ('medical_services', 'خدمات درمانی'), ('housewives', 'زنان خانه دار'), ('rural', 'روستاییان'), ('iranian_health', 'سلامت ایرانیان'), ('universal_health', 'سلامت همگانی'), ('gov_employees', 'سلامت - کارکنان دولت'), ('other_sectors', 'سلامت - سایر اقشار'), ('armed_forces', 'نیروهای مسلح'), ('special_patients', 'بیماران خاص')], max_length=50, null=True, verbose_name='وضعیت بیمه'),
        ),
        migrations.AlterField(
            model_name='case',
            name='job',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شغل'),
        ),
    ]
