# Generated by Django 6.0 on 2025-12-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_alter_case_address_alter_case_field_of_study_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='job',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شغل'),
        ),
    ]
