# Generated by Django 6.0 on 2025-12-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_alter_case_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='military_serveice',
            field=models.CharField(blank=True, choices=[('absence', 'غیبت'), ('exempt', 'معافیت'), ('passed', 'گذرانده')], max_length=30, null=True, verbose_name='وضعیت سربازی'),
        ),
    ]
