# Generated by Django 6.0 on 2025-12-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_alter_case_military_serveice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoveredreasoncase',
            name='reason',
            field=models.CharField(blank=True, choices=[('employment_loan', 'وام اشتغال'), ('insurance_right', 'حق بیمه'), ('cost_reduction', 'کاهش هزینه انشعابات')], max_length=500, null=True),
        ),
    ]
