# Generated by Django 6.0 on 2025-12-05 00:18

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_alter_recoveredreasoncase_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disability',
            name='disability_type',
            field=models.CharField(choices=[('body_movment', 'جسمی حرکتی'), ('body_movment_ms', 'جسمی حرکتی(ام اس)'), ('nerves_psyche', 'اعصاب و روان'), ('hearing', 'شنوایی'), ('vision', 'بینایی'), ('mental', 'ذهنی'), ('spoken', 'گفتاری'), ('autism', 'اوتیسم'), ('spinal_cord', 'ضایعه نخاعی'), ('old_age', 'سالمندی'), ('alzheimer', 'آلزایمر'), ('dementia', 'دمانس'), ('no_disability', 'فاقد معلولیت'), ('no_document', 'فاقد مدارک لازم')], max_length=30, verbose_name='نوع معلولیت'),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', django_jalali.db.models.jDateField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
        ),
    ]
