# Generated by Django 6.0 on 2025-12-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_alter_casenotes_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casenotes',
            name='note',
            field=models.TextField(),
        ),
    ]
