# Generated by Django 6.0 on 2025-12-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_alter_casenotes_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefamilymembers',
            name='education',
            field=models.CharField(blank=True, choices=[('illiterate', 'بی سواد'), ('elementary', 'ابتدایی'), ('middle_school', 'متوسطه اول (سیکل)'), ('high_school', 'متوسطه دوم (دیپلم)'), ('associate', 'کاردانی (فوق دیپلم)'), ('bachelor', 'کارشناسی (لیسانس)'), ('master', 'کارشناسی ارشد (فوق لیسانس)'), ('phd', 'دکترا'), ('post_doc', 'فوق دکترا')], max_length=30, null=True, verbose_name='تحصیلات'),
        ),
    ]
