# Generated by Django 6.0 on 2025-12-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_alter_casefamilymembers_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefamilymembers',
            name='job',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شغل'),
        ),
    ]
