# Generated by Django 6.0 on 2025-12-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_alter_casefamilymembers_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='house_mortgage',
            field=models.IntegerField(blank=True, null=True, verbose_name='رهن'),
        ),
        migrations.AddField(
            model_name='case',
            name='house_rent',
            field=models.IntegerField(blank=True, null=True, verbose_name='اجاره'),
        ),
    ]
