# Generated by Django 6.0 on 2025-12-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_case_house_mortgage_case_house_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='house_rent',
            field=models.FloatField(blank=True, null=True, verbose_name='اجاره'),
        ),
    ]
