# Generated by Django 6.0 on 2025-12-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_alter_case_house_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedocuments',
            name='expiry_diuration',
            field=models.FloatField(blank=True, choices=[(5, '5 سال بعد'), (10, '10 سال بعد'), (1, '1 سال بعد'), (2, '2 سال بعد'), (3, '3 سال بعد'), (4, '4 سال بعد'), (6, '6 سال بعد'), (7, '7 سال بعد'), (8, '8 سال بعد'), (9, '9 سال بعد'), (0.5, '6 ماه بعد')], null=True),
        ),
        migrations.AlterField(
            model_name='casefamilymembers',
            name='relation',
            field=models.CharField(choices=[('father', 'پدر'), ('mother', 'مادر'), ('brother', 'برادر'), ('sister', 'خواهر'), ('son', 'پسر'), ('daughter', 'دختر'), ('husband', 'شوهر'), ('wife', 'زن')], max_length=30, verbose_name='نسبت'),
        ),
    ]
