# Generated by Django 6.0 on 2025-12-05 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0019_alter_casedocuments_expiry_diuration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visits",
                to="cases.case",
            ),
        ),
    ]
