# Generated by Django 6.0 on 2025-12-06 17:42

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0020_alter_visit_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=500, verbose_name='عنوان درخواست')),
                ('date', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='Services_provided',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=500, verbose_name='خدمت ارائه شده')),
                ('date', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_provided', to='cases.case')),
            ],
        ),
    ]
