# Generated by Django 6.0 on 2025-12-06 18:13

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_demands_services_provided'),
    ]

    operations = [
        migrations.AddField(
            model_name='casenotes',
            name='date',
            field=django_jalali.db.models.jDateField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='casenotes',
            name='note',
            field=models.TextField(verbose_name='متن یادداشت'),
        ),
    ]
