# Generated by Django 6.0 on 2025-12-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_casenotes_date_alter_casenotes_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefamilymembers',
            name='relation',
            field=models.CharField(choices=[('father', 'پدر'), ('mother', 'مادر'), ('husband', 'همسر'), ('brother', 'برادر'), ('sister', 'خواهر'), ('son', 'پسر'), ('daughter', 'دختر')], max_length=30, verbose_name='نسبت'),
        ),
    ]
