# Generated by Django 5.2.7 on 2026-07-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0023_alter_casefamilymembers_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='apartment_area',
            field=models.IntegerField(blank=True, null=True, verbose_name='متراژ آپارتمان'),
        ),
        migrations.AddField(
            model_name='case',
            name='building_type',
            field=models.CharField(blank=True, choices=[('apartment', 'آپارتمان'), ('villa', 'ویلایی'), ('basement', 'زیرزمین مسکونی'), ('other', 'سایر')], max_length=30, null=True, verbose_name='نوع ساختمان'),
        ),
        migrations.AddField(
            model_name='case',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی'),
        ),
        migrations.AddField(
            model_name='case',
            name='room_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد اتاق'),
        ),
        migrations.AlterField(
            model_name='case',
            name='military_serveice',
            field=models.CharField(blank=True, choices=[('absence', 'غیبت'), ('exempt', 'معافیت'), ('passed', 'گذرانده'), ('not_aged', 'زیر سن سربازی')], max_length=30, null=True, verbose_name='وضعیت سربازی'),
        ),
    ]
