# Generated by Django 6.0 on 2026-08-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0024_case_apartment_area_case_building_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='آرشیو شده'),
        ),
    ]
